### ISSUE TITLE
Discovery does not work

### ISSUE THREAD

**Issue by frol** [seemoo-lab/opendrop#1]
I can neither get my laptop discovered nor discover my apple devices from the laptop.

My laptop configuration:

* Arch Linux / x64 / 4.19.46 LTS kernel
* Wireless card: Intel 7260 (I have already used it in a monitor mode with airdump-ng, so it works fine)
* Latest `owl` from git (I have created an [AUR package](https://aur.archlinux.org/packages/owl-git/))

My iPhone SE and iPad Air2 have the latest stable iOS 12.3.1.

I have tried various setups on my laptop:

* Connected to 5 GHz WiFi network (the same as the Apple devices) with NetworkManager. The result seems to be that `owl` couldn't get any useful information:

    ```
    19:21:13 INFO : WLAN device: mon0 (addr 28:b2:bd:3:b9:d9)
    19:21:13 INFO : Host device: awdl0
    19:21:13 DEBUG: switch channel to 6 (slot 0)
    19:21:13 TRACE: send MIF
    19:21:13 TRACE: Send data (len 126) to 33:33:0:0:0:16 (0.0.38)
    19:21:13 TRACE: send MIF
    19:21:13 TRACE: send PSF
    19:21:13 TRACE: send MIF
    19:21:13 TRACE: send PSF
    19:21:13 TRACE: send MIF
    ```

    `opendrop` on both `receive` and `find` (with `-d` flag) was silent except the initial message.
* Connected to 2.4 GHz WiFi network (reconnected all the Apple devices there as well) with NetworkManager. The result was `ERROR: unable to inject packet (send: Resource temporarily unavailable)` output from `owl`.
* Disconnected from all the WiFi networks (the Apple devices are left connected to 2.4 GHz WiFi network). This mode was the most promising, at least I started getting some useful messages on the `owl` side:

    ```
    19:27:58 INFO : WLAN device: wlp8s0mon (addr 28:b2:bd:3:b9:d9)
    19:27:58 INFO : Host device: awdl0
    19:27:58 DEBUG: switch channel to 6 (slot 0)
    19:28:27 DEBUG: peer 3e:50:c6:71:d8:5f () changed channel sequence to 149,149,149,149,0,0,0,0,6,149,149,149,0,0,0,0
    19:28:27 DEBUG: new election tree: 28:b2:bd:3:b9:d9 -> 3e:50:c6:71:d8:5f (met 60, ctr 174)
    19:28:27 INFO : add peer 3e:50:c6:71:d8:5f ()
    19:28:29 DEBUG: peer 3e:50:c6:71:d8:5f () changed channel sequence to 149,149,149,0,0,0,0,0,6,149,149,0,0,0,0,0
    19:28:32 DEBUG: new election tree: 28:b2:bd:3:b9:d9 -> 3e:50:c6:71:d8:5f -> da:65:4:e9:8d:fa (met 536, ctr 135)
    19:28:34 DEBUG: peer 3e:50:c6:71:d8:5f () changed channel sequence to 149,0,0,0,0,0,0,0,6,149,149,0,0,0,0,0
    19:28:35 DEBUG: peer 3e:50:c6:71:d8:5f () changed channel sequence to 149,149,149,149,0,0,0,0,6,6,6,6,0,0,0,0
    19:28:37 DEBUG: peer 3e:50:c6:71:d8:5f () changed channel sequence to 149,149,149,0,0,0,0,0,6,6,6,0,0,0,0,0
    19:28:46 DEBUG: peer 3e:50:c6:71:d8:5f () changed channel sequence to 149,0,0,0,0,0,0,0,6,6,6,0,0,0,0,0
    ...
    19:32:47 INFO : remove peer 16:8c:3a:d8:ab:13 (iPad)
    19:32:47 DEBUG: new election tree: 28:b2:bd:3:b9:d9 (met 60, ctr 0)
    19:35:35 DEBUG: peer 4a:a7:d4:66:97:34 () changed channel sequence to 149,149,149,149,0,0,0,0,6,149,149,149,0,0,0,0
    19:35:35 INFO : add peer 4a:a7:d4:66:97:34 (iPad)
    19:35:35 DEBUG: new election tree: 28:b2:bd:3:b9:d9 -> 4a:a7:d4:66:97:34 (met 60, ctr 236)
    19:35:37 DEBUG: peer 4a:a7:d4:66:97:34 (iPad) changed channel sequence to 149,149,149,0,0,0,0,0,6,149,149,0,0,0,0,0
    19:35:42 DEBUG: peer 4a:a7:d4:66:97:34 (iPad) changed channel sequence to 149,0,0,0,0,0,0,0,6,149,149,0,0,0,0,0
    19:35:43 DEBUG: peer 4a:a7:d4:66:97:34 (iPad) changed channel sequence to 149,0,0,0,0,0,0,0,6,6,6,0,0,0,0,0
    ```

    NOTE: My iPhone has no name for some reason while my iPad has.

    On the opendrop side I have seen a useful message only once:

    ```
    $ opendrop find -d
    2019-05-29 19:30:39,952 INFO     opendrop.cli: Looking for receivers. Press enter to stop ...
    2019-05-29 19:31:52,144 DEBUG    opendrop.client: Add service c8d4309875b0._airdrop._tcp.local.
    2019-05-29 19:31:52,144 DEBUG    opendrop.cli: AirDrop service found: iPad.local., fe80::148c:3aff:fed8:ab13:8770, ID c8d4309875b0
    2019-05-29 19:31:52,144 DEBUG    opendrop.client: Send /Discover request


    2019-05-29 19:32:16,459 DEBUG    opendrop.cli: Save discovery results to /home/frol/.opendrop/discover.last.json
    ```

    I still could not send a file.

**Comment by schmittner** [comment]
Two things to try out:
* It appears that you live in a regdom where channel 149 is allowed, so you can try to run `owl` with `-c 149` to use that channel. Using a 5 GHz channel will increase the overlap (see channel sequence) with your Apple devices.
* I have only tested `owl` with exclusive access to the Wi-Fi chip, so I would definitely disconnect from all other networks.
