### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by BitterRose** [seemoo-lab/opendrop#109]
Can anyone confirm that this repository still works with the latest iOS?  I'm having some issues with OWL, but I suppose it's not compatible with iOS 16.

**Comment by amateusz** [comment]
Hey, I tried to run it and seems not to work with iOS 16.

I'm able to run `owl` with no errors, but `opendrop` does not do anything.
This is what I get when opening a "Share" → "AirDrop" window on an iPhone, and then close it:
```
13:26:12 INFO : add peer 7e:da:3d:bb:xx:xx ()
13:26:22 INFO : remove peer 7e:da:3d:bb:xx:xx ()
```
which seems correct. Yet `opendrop find` nor `opendrop receive`  does anything (the device does not show up on iPhone):
```
$ opendrop find
Looking for receivers. Press Ctrl+C to stop ...
^C
$ opendrop receive
Announcing service: host mateusz-dziedzic, address fe80::4603:2cff:xxxx:xxxx, port 8771
Starting HTTPS server
```

**Comment by Binozo** [comment]
Confirmed working on Raspberry pi 4B <-> macOS Ventura `13.4.1` (latest)

On my part I needed to make sure that my devices could see each other through bluetooth

**Comment by WuYingzheng** [comment]
> Confirmed working on Raspberry pi 4B <-> macOS Ventura `13.4.1` (latest)
> 
> On my part I needed to make sure that my devices could see each other through Bluetooth 

can you send from macOS to iOS?

**Comment by Binozo** [comment]
> > Confirmed working on Raspberry pi 4B <-> macOS Ventura `13.4.1` (latest)
> > On my part I needed to make sure that my devices could see each other through Bluetooth
> 
> can you send from macOS to iOS?

Sorry I don't have an iPhone, I can't test that

**Comment by MortRainey** [comment]
> > Confirmed working on Raspberry pi 4B <-> macOS Ventura `13.4.1` (latest)
> > On my part I needed to make sure that my devices could see each other through Bluetooth
> 
> can you send from macOS to iOS?

you don't need opendrop to send files from MacOS to iOS. These clients do AirDorp nativly ...

**Comment by littleblack111** [comment]
> Hey, I tried to run it and seems not to work with iOS 16.
> 
> I'm able to run `owl` with no errors, but `opendrop` does not do anything. This is what I get when opening a "Share" → "AirDrop" window on an iPhone, and then closing it:
> 
> ```
> 13:26:12 INFO : add peer 7e:da:3d:bb:xx:xx ()
> 13:26:22 INFO : remove peer 7e:da:3d:bb:xx:xx ()
> ```
> 
> which seems correct. Yet `opendrop find` nor `opendrop receive` does anything (the device does not show up on iPhone):
> 
> ```
> $ opendrop find
> Looking for receivers. Press Ctrl+C to stop ...
> ^C
> $ opendrop receive
> Announcing service: host mateusz-dziedzic, address fe80::4603:2cff:xxxx:xxxx, port 8771
> Starting HTTPS server
> ```

same I post another issue #119 , owl give the adding peers etc output, but opendrop recive does nothing

**Comment by littleblack111** [comment]
> Could confirm this issue. Tried running OpenDrop using my apple certificates but sadly my pi and `macos 14 Sonoma` can't find each other.
> 
> I assume apple changed the way discovery and overall the protocol works :/

Yep, me too, I am running macOS sonoma on my macbook. but then my iphone doesn't work as well
