### ISSUE TITLE
AirPlay 2

### ISSUE THREAD

**Issue by NSExceptional** [seemoo-lab/opendrop#11]
Does this support AirPlay 2?

**Comment by tomscholz** [comment]
Hey @NSExceptional ,
this project is _"an open Apple AirDrop implementation"_.
AirDrop (Sharing files between iDevices) is not be confused with AirPlay(Playing music/video wirelessy to screens and audio systems).

Hope this helps.

Cheers,
Tom

**Comment by NSExceptional** [comment]
Oof. My bad. So what happened was I sent this repo to someone else, and they were like "Cool! Now we need one for AirPlay too!" And I guess I had a brain-fart and forgot this was AirDROP and not AirPLAY. 😅
