### ISSUE TITLE
Crypto airdrop tool for coins, tokens, and NFTs

### ISSUE THREAD

**Issue by ogpadmin** [seemoo-lab/opendrop#121]
If anyone came here looking for an airdrop utility check out [OGP Bulk Sender](https://offgridplatform.com/apps/bulk-sender)!

**Comment by deep2web** [comment]
What is the conncetion to an opendrop Issue?

**Comment by wurstcase** [comment]
> What is the conncetion to an opendrop Issue?

The secret ingredient is crime
