### ISSUE TITLE
owl issue 

### ISSUE THREAD

**Issue by UchihaSR** [seemoo-lab/opendrop#22]
Make sure that `owl` is running.'.format(config.interface))
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running.

**Comment by schmittner** [comment]
Well, have you installed and started [`owl`](https://github.com/seemoo-lab/owl)? I guess not...

**Comment by UchihaSR** [comment]
I have installed the owl after i came to know about it. after running ifconfig command, my wireless-interface is wlp3s0, the out
![owl_issue](https://user-images.githubusercontent.com/52357560/65349177-6db1f280-dc00-11e9-9367-68166dae2695.png)
put is

**Comment by schmittner** [comment]
It appears that your Wi-Fi card/driver does not support active monitor mode. Please check the owl repo for details. I'm closing this since it's not related to opendrop.

**Comment by PhilipMachineLearning** [comment]
> I have installed the owl after i came to know about it. after running ifconfig command, my wireless-interface is wlp3s0, the output is
> ![owl_issue](https://user-images.githubusercontent.com/52357560/65349177-6db1f280-dc00-11e9-9367-68166dae2695.png)

Same issue here

**Comment by ioquatix** [comment]
I don't have wireless... does opendrop work on fixed ethernet? lol :p

**Comment by Ocelot124286** [comment]
Owl creates a tap0 interface on Mac instead of awdl0. How can I get around that?

**Comment by schmittner** [comment]
Please post issues regarding `owl` in the respective repository.
