### ISSUE TITLE
wlan0, device can't be found

### ISSUE THREAD

**Issue by SniparsZach** [seemoo-lab/opendrop#23]
Whenver I put in
`sudo iw phy `iw dev wlan0 info | gawk '/wiphy/ {printf "phy" $2}'` interface add mon0 type monitor
`

I get:
`command failed: No such device (-19)
command failed: No such file or directory (-2)
`

**Comment by schmittner** [comment]
Seems like you don't have a network interface called `wlan0`.

**Comment by SniparsZach** [comment]
> Seems like you don't have a network interface called `wlan0`.

Yeah it was after installing the new firmware from Nexmon

**Comment by schmittner** [comment]
I'm closing this since its not directly related to OpenDrop.
