### ISSUE TITLE
Random behaviour with opendrop receive

### ISSUE THREAD

**Issue by lucferbux** [seemoo-lab/opendrop#24]
Hi, I've tried in multiple virtual machines with the following configuration the "receive" command with no success:

- Ubuntu 18.04, network card: Alpha AWUS052NH
- Debian 9, network card: Alpha AWUS052NH
- Kali Linux 2019, network card: Alpha AWUS052NH

In all of the environments, I've managed to set up the network with the card in monitor mode, although I have only been able to run the owl process with the -N flag `sudo owl -i [iface] -N`
When i run the process (both with the daemon process or without it) I've been able to use the `opendrop find` command all the time, discovering all the devices but when i try to run `opendrop receive` there are some random issues:

- Most of the time it does not work, freezing and sending random zerconf mdns packets but not receiven anything.
- Sometimes it captures the devices and my iDevices display the new device created by opendrop with the given name.
- Sometimes it captures the devices but it does not appear in my iDevices.

So I don't know what to do to fix those issues.
Thanks in advance.

**Comment by lucferbux** [comment]
There's another setup I've tried:

- Ubutnu 18.04 but fresh installed in a host machine (not virtual machine) with another alpha card.

**Comment by lucferbux** [comment]
Ok, I think I've found the error. If you run opendrop in a virtual machine in a mac host, the airdrop service will override the opendrop service, in order to make it work, it is mandatory to disable both Wifi and Bluetooth in the host machine (mac) and use an external card in the VM.

**Comment by schmittner** [comment]
Hmm, that does not sound very plausible to me since you are using for own physical Wi-Fi card within the guest. The erratic behavior seems to have to to with the fact that your card does not support active monitor mode (see https://github.com/seemoo-lab/owl/issues/9, why else would you need `-N`?)

**Comment by lucferbux** [comment]
Yes it’s true, I don’t know why the bad performance  somehow made me believe it was the problem, so that’s the reason, please could you suggest me any card that supports active monitor?
It’s the first time I’ve heard of that and I don’t know where to start to test this mode now that i know my alpha card doesn’t support it.

Thanks again, really appreciate your work.

**Comment by lucferbux** [comment]
Ok, I’ve read the docs of owl, any other external card that could possibly support active monitore mode? Thank you in advance.

**Comment by schmittner** [comment]
According to https://github.com/seemoo-lab/owl/issues/10, the TP-Link Archer T1U (mt76 driver) seems to work.
