### ISSUE TITLE
DistributionNotFound

### ISSUE THREAD

**Issue by cvanelteren** [seemoo-lab/opendrop#33]
On manjaro I'm getting the following error after installing **opendrop-git** from aur. 

    pkg_resources.DistributionNotFound: The 'ipaddress' distribution was not found and is required by ifaddr

After some googling I can't find where this distribution is supposed to come from. Can you point me to the right direction?

**Comment by schmittner** [comment]
I'm not maintaining the aur package. Have you tried installing from source?

**Comment by schmittner** [comment]
Closing this as stale.
