### ISSUE TITLE
Cant find my iphone

### ISSUE THREAD

**Issue by UtechtDustin** [seemoo-lab/opendrop#43]
This project looks awesome, but sadly its not working for me.
I installed owl und opendrop, then i set the wifi adapter in monitor mode
```
$ sudo ifconfig wlx74da38ea5fe5 down
$ sudo iwconfig wlx74da38ea5fe5 mode monitor
```

After that i started owl
```
$ sudo owl -i wlx74da38ea5fe5 -N
```

Anything looks like its working, i get the following output from owl
```
13:24:08 INFO : WLAN device: wlx74da38ea5fe5 (addr 74:da:38:ea:5f:e5)
13:24:08 INFO : Host device: awdl0
```

Also the output from opendrop (`opendrop find`) has no exceptions/error messages
```
Looking for receivers. Press enter to stop ...
```

But i never find my iphone (Iphone 11 pro), the same thing is while receive (my iphone dont find my pc).

I hope you can help me out :-)

**Comment by spadejack014** [comment]
After an iOS update in 2019, Opendrop was unable to find and transfer files to an iPhone. Fortunately, the airdrop on iOS can still discover and transfer files to opendrop.

**Comment by Sn0wfreezeDev** [comment]
Hi, 

this could be an issue related to OWL. 
The general features of finding seems to work on OpenDrop (tested on macOS without OWL). 
Currently we have an issue with OWL on macOS Catalina. I will update you if we discovered the source. 

- Alex

**Comment by Sn0wfreezeDev** [comment]
Hi, 

I resolved it and it is related to the Bluetooth Low Energy messages. The devices won't connect with each other before they have received a BLE advertisement. The receive method does not depend on BLE. Please check out the answer here https://github.com/seemoo-lab/opendrop/issues/51 for a detailed description. 

Kind regards 
Alexander Heinrich
