### ISSUE TITLE
Unable to install, issue with python version

### ISSUE THREAD

**Issue by jlukanc1** [seemoo-lab/opendrop#44]
I am unable to install using pip3, with the following error:

> ERROR: Package 'opendrop' requires a different Python: 3.5.3 not in '>=3.6'

**Comment by EthanZoneCoding** [comment]
I am having the same issue, and am trying to fix it rn. I will they to you if I fix it

**Comment by EvanMu96** [comment]
Plz carefully read the requirement in the README file. This repo requires a Python version >=3.6.
You should install a Python with a higher version(>=3.6) to fix this problem.

**Comment by jlukanc1** [comment]
Yes, I know that, I had python 3.7 installed

**Comment by schmittner** [comment]
But you apparently have an older version installed as well and pip3 is from that version.
