### ISSUE TITLE
Code restructuring

### ISSUE THREAD

**Issue by vinaysb** [seemoo-lab/opendrop#45]
Hello, I was wondering if you would be ok with me changing the setup files to current standards, so that the main config entries, such as requirements, script name, entry point, are in the setup.cfg. 

Also using click library instead for CLI

**Comment by schmittner** [comment]
HI @vinaysb, creating setup.cfg is a good idea.

However, I do not see a reason to use a non-standard CLI library. I would like to keep dependencies as low as possible.

**Comment by vinaysb** [comment]
Ok great, I made the changes in my fork. I had to change the tree structure, by having an intermediary src folder, otherwise relative imports would break.

**Comment by vinaysb** [comment]
Also, click is used for making the code look much neater with the help of decorators, groups & commands. You will also have help argument created for you by default

https://docs.python-guide.org/scenarios/cli/
