### ISSUE TITLE
No image preview when sending images to iPhone

### ISSUE THREAD

**Issue by wkpn** [seemoo-lab/opendrop#47]
title^

debugging shows that `FileIcon` from [this line](https://github.com/seemoo-lab/opendrop/blob/master/opendrop/util.py#L176) definitely has some bytes in it, but upon receiving no preview is available, just the plain text 

Expected behavior: [this](https://hsto.org/webt/bc/ss/2v/bcss2v52pngof8z3dgex5rnz5q4.png)

Actual behavior: same but without an image

**Comment by schmittner** [comment]
What‘s the iOS version?
Does this happen with all source files?
Can you send an example?

**Comment by wkpn** [comment]
iOS version: latest, 13.4.1
I've tried `jpg`, `png` and it was all the same no matter what the image was
Interestingly enough, when sending images to MacBook, notification has the preview, while there is nothing on the iOS

**Comment by schmittner** [comment]
I just confirmed this.

It might be that Apple has changed something regarding the preview format for iOS (used to be JPEG2000). We'll check if something has changed, but this may take some time.

**Comment by wkpn** [comment]
I've just read the wiki and [it says that Apple has disabled preview from non-contacts](https://en.wikipedia.org/wiki/AirDrop#Security_and_privacy).

Looks like it is iOS thing and has nothing to do with preview formats ([source](https://japantoday.com/category/tech/social-plague-of-%27airdrop-chikan%27-wiped-out-with-simple-change-in-ios-13-update))

**Comment by schmittner** [comment]
Thanks for the info. So, it's expected behavior.
