### ISSUE TITLE
[question]ipadOS no detected

### ISSUE THREAD

**Issue by ariagecheney** [seemoo-lab/opendrop#51]
1.   mbp 2019 13.3' ,macos catalina 10.15.4, ipad 2018 ipadOS 13.3.1;
2  mbp has installed opendrop, see picture below,i hava set my ipad [discoverable]
**however ,It is set to be discoverable by everyone but it still won't be detected.**
![IMG_68F0AC9A6E5A-1](https://user-images.githubusercontent.com/35078844/84402659-4f30d300-ac37-11ea-940c-7a68104a6172.jpeg)
on mbp, i exec"opendrop find ", only get "Found  index 0  ID d3a72bda7ed7  name chenhuiying的MacBook Pro", see below.
![seeblow](https://user-images.githubusercontent.com/35078844/84402957-b6e71e00-ac37-11ea-8cbf-06a5e5c1c063.png)
so i want my ipad to be found  by opendrop. how could i do ?
And more often than not, I just get"Looking for receivers. Press enter to stop ...",  Nothing，see below
![nothing](https://user-images.githubusercontent.com/35078844/84403704-923f7600-ac38-11ea-942a-0041e1b322f1.png)

**Comment by Sn0wfreezeDev** [comment]
There are currently issues on macOS devices with T2 chips and OWL. 
I was able to reproduce your issue on my MacBook Pro 2019, 15". We will look into it and see if we can deliver a fix for this next week.

**Comment by Sn0wfreezeDev** [comment]
Hi, 
After some investigation we discovered that this is a known issue depending on Bluetooth Low Energy (BLE) messages. Our current implementation is network only and to discover your devices AirDrop normally sends BLE advertisements at first. Those advertisements inform all surrounding devices that an AirDrop sender is looking for devices. After they have received this advertisement they will activate their AWDL interface and set up a peer-to-peer connection to your Mac. 

In fact, you can solve this issue by opening AirDrop in Finder. Then you Mac will start sending the BLE advertisements. Then OpenDrop will also find all devices: 
```
Found  index 3  ID 2ac218d3d881  name 🤔 
```

Kind regards 
Alexander Heinrich
