### ISSUE TITLE
Share password via opendrop

### ISSUE THREAD

**Issue by lrlunin** [seemoo-lab/opendrop#52]
Hello, it is possible to share a WLAN password via AirDrop since couple of last iOS versions. Could it be also done with this library?

**Comment by schmittner** [comment]
Apple's Wi-Fi password sharing service does not use the AirDrop protocol, so it's not possible to implement this feature with OpenDrop.

However, we have already been working on the password sharing protocol (which is BLE-only) and will release something soon which we will also feature on our [website](https://owlink.org). Stay tuned :-)
