### ISSUE TITLE
Always get low transfer speed.

### ISSUE THREAD

**Issue by MrSwiss** [seemoo-lab/opendrop#6]
Hi, I use build-in raspberry pi zero wifi for receiving file from my friend iPad, My speed is around 0.05 - 0.30 MB/s.

I don't know what cause this or this is normal for opendrop. I think its because I use build in antenna. I plan to buy new wifi usb to boost up my speed.

**Comment by schmittner** [comment]
I have the same issue on the Raspberry Pi. In fact, I believe that it's a "problem" with Nexmon and frame injection/reception over the monitor interface are the bottleneck. If you run OWL/OpenDrop on a different platform, e.g., on a Mac or Linux with an AR9280 chip, transfer rates are _much_ better.
