### ISSUE TITLE
Error bringing mon0 up following successful install on Raspberry Pi

### ISSUE THREAD

**Issue by ElevonsJKeloids** [seemoo-lab/opendrop#64]
Upon running ```sudo iw phy `iw dev wlan0 info | gawk '/wiphy/ {printf "phy" $2}'` interface add mon0 type monitor``` I get the output `command failed: Operation not supported (-95)`

Any ideas?

**Comment by schmittner** [comment]
This seems to be an issue with your Nexmon setup. Please check out their installation instructions at https://github.com/seemoo-lab/nexmon
