### ISSUE TITLE
Question: Is it possible to specify the broadcast hostname? e.g. From <Device_name>.local to a custom one.

### ISSUE THREAD

**Issue by acheong08** [seemoo-lab/opendrop#66]

**Comment by VladislavEkimtcov** [comment]
`-n NAME, --name NAME  Computer name (displayed in sharing pane)`
  
Other devies will see you as specified with the --name tag

**Comment by schmittner** [comment]
If you really want to change the advertised hostname in the mDNS responses (which is not displayed to AirDrop users), you can pass this a parameter to the `AirDropConfig` class:

https://github.com/seemoo-lab/opendrop/blob/bc7813bf915b0384c6c3327d0d13795f3bca8fe7/opendrop/config.py#L54-L57

**Comment by acheong08** [comment]
Ok thanks.

**Comment by acheong08** [comment]
I was confused by `Announcing service: host raspberrypi.local` even though I specified `-n`. It works in practice though.
