### ISSUE TITLE
Sending URLs does not work

### ISSUE THREAD

**Issue by VladislavEkimtcov** [seemoo-lab/opendrop#67]
I am planning on hosting an app launch party. One idea is to have a jockey copy-paste device IDs from one terminal window into another with a send script, sharing urls to a landing webpage with an app clip banner to the participants, logging their responses (or have a computer do something similar). We are doing this because we're are investigating AirDrop as a marketing method among youth. 

The problems start at the conceptual stage. I've tried airdropping a webpage to an OpenDrop receiver, and got a *.webloc file. Great. The file starts with bplist00 and is similar to a file you get by dragging a safari url onto desktop. 

The problem is, when I try to opendrop the exact same file back, I get this:

<img src="https://i.imgur.com/yWhVDfW.png" width="20%">

Mysteriously, airdropping the file seems to work fine and launches Safari on the iPhone. 

Does this have to do something with the specifics of the send_upload implementation? Does OpenDrop not advertise some sort of capability?

ps Thank you for your amazingly interesting paper and all the effort of making airdrop open :)

**Comment by VladislavEkimtcov** [comment]
https://github.com/seemoo-lab/opendrop/issues/56
Is webloc one of these types?

**Comment by VladislavEkimtcov** [comment]
note to not sleep deprived tomorrow self: webloc is "application/octet-stream" mime type

**Comment by schmittner** [comment]
This one was really not trivial, had to dig a bit deeper. You can now specify a `--url` flag to state that `-f,--file` should in fact be treated as an URL. The solution only works for devices that announce support for URLs (which most current Apple devices do as far as I know). Let me know if it works for you.
