### ISSUE TITLE
Discovers macbooks (no phones)

### ISSUE THREAD

**Issue by notnotwest** [seemoo-lab/opendrop#75]
start opendrop with 
opendrop -i wlp1s0 find (no owl because it doesnt work with it at all)
lists macbooks when triggered by opening airdrop menu on phone
no phones are triggered, even with everyone mode on
receive mode starts server then doesnt show up on iphone 12 mini or other devices

**Comment by Sn0wfreezeDev** [comment]
Without OWL you won't find any iPhones. 
iPhones only use AWDL to send AirDrop files, while MacBooks are able to send files over any other network type as well (Wi-Fi or Ethernet).

**Comment by lucasromeiro** [comment]
Hello everyone, this happened in the first step to get the keys:

![image](https://user-images.githubusercontent.com/2086543/220122693-248d8527-7e56-4ffd-805a-50d6554b6e27.png)


I continued the tutorial normally, but when I run the make command I get this error:

![image](https://user-images.githubusercontent.com/2086543/220122869-6bb240a3-a9cc-489c-8232-8946c903fa0f.png)


Can someone help me?

My MAC is a MacStudio with M1 Max and MAC OS 13.1 (22C65) (ventura).


Please, help...
