### ISSUE TITLE
[Question] Whether this works for non-darwin devices transforming data wirelessly?

### ISSUE THREAD

**Issue by ryuujo1573** [seemoo-lab/opendrop#78]
I am trying to figure out the AirDrop workflows and harvest the convenience in placing this practice into several non-apple devices with "AirSpeed"
Or is there any way to send data wirelessly in a speed fast enough that is no far from AirDrop? I was astonished by send gigabytes in few seconds from my first macbook to others

Any kind of reply would help, and thank you for your precious work!

**Comment by TheLastGimbus** [comment]
Read README.md. TL;DR yes, but you need a wifi card that supports "active monitor mode" - I ran this kinda sucessfully on my Ubuntu, but I've only sucessfully received now - not send
