### ISSUE TITLE
Create "opendrop" package for pip installation

### ISSUE THREAD

**Issue by bf** [seemoo-lab/opendrop#8]
Currently the command `pip3 install opendrop` shows that the package is not registered in the PIP repositories yet, therefore it is easy for someone malicious to claim the package and serve arbitrary code with it.

I suggest the maintainers of this project register it with PIP so it can be installed with above-mentioned command.

**Comment by SEJeff** [comment]
This would require sending the changes to python-zeroconf back upstream first.

**Comment by jsjohnst** [comment]
@SEJeff I would still recommend putting a placeholder package up for the reasons indicated by @bf. If you don't, someone else will.

**Comment by SEJeff** [comment]
@jsjohnst agreed, but a placeholder, not the full version.

**Comment by schmittner** [comment]
Thanks @bf, that's a valid concern.

I've created a placeholder project at pypi.org. I'll publish releases there if the projects becomes more mature.

**Comment by jstasiak** [comment]
> This would require sending the changes to python-zeroconf back upstream first.

I don't think it's *required* strictly speaking, but I'd be interested in having the changes upstream regardless. :)

Note that there's been some work on IPv6 (notably https://github.com/jstasiak/python-zeroconf/pull/174) so there may be some clash here as the readme says
> We use a modified version of the python-zeroconf package (essentially adding rudimentary IPv6 and AWDL support)

I'm sure we'll work something out though.

PS. Nice project!

**Comment by schmittner** [comment]
The package is available at https://pypi.org/project/opendrop/
