### ISSUE TITLE
Can this send/receive without "Apple-signed certificates"

### ISSUE THREAD

**Issue by Taihenc** [seemoo-lab/opendrop#98]
- According to [GOOpenDrop](https://github.com/bodaay/GoOpenDrop) it's seem like even in everybody mode its need to have cert to be able send/receive to Apple devices
- I can send/receive between Linux Devices. But I never try to send/receive to Apple Devices (cause I don't have any of them)
**Is any of you can send/receive to Apple devices without cert??**

**Comment by Taihenc** [comment]
So to answer the question, I just bought an Apple device😆 and it's work I can send/recieve file. without Apple extracted key.

**Comment by lucasromeiro** [comment]
@Taihenc 
Hello, I didn't understand very well, can you send files without the keys? I am unable to extract the keys here, could you help me?


My case:

Hello everyone, this happened in the first step to get the keys:

![image](https://user-images.githubusercontent.com/2086543/220122693-248d8527-7e56-4ffd-805a-50d6554b6e27.png)


I continued the tutorial normally, but when I run the make command I get this error:

![image](https://user-images.githubusercontent.com/2086543/220122869-6bb240a3-a9cc-489c-8232-8946c903fa0f.png)


Can someone help me?

My MAC is a MacStudio with M1 Max and MAC OS 13.1 (22C65) (ventura).


Please, help...

**Comment by Taihenc** [comment]
Yes, I can send files without the keys (Ubuntu 22.04 <-> iPad iOS 16.1✅). Without the key, some [benefit](https://github.com/bodaay/GoOpenDrop#extraction-of-the-keys-benefits), but it still works. Unfortunately, I can't help extract the key because it can only be obtained from a Mac, and I don't have any of them.

**Comment by lucasromeiro** [comment]
> Yes, I can send files without the keys (Ubuntu 22.04 <-> iPad iOS 16.1✅). Without the key, some [benefit](https://github.com/bodaay/GoOpenDrop#extraction-of-the-keys-benefits) are lost, but it still works. Unfortunately, I can't help extract the key because it can only be obtained from a Mac, and I don't have any of them.

I managed to extract the keys!!  thanks for the help, you were right.  at the end of the I needed to adjust my developer certificate which was a user and not an administrator.

now i have just installed ubuntu on a raspberry pi for you to use.  however, I still don't understand how to install and operate this code… I intend to use python to use it, could you give me any tips on how to install and use it?  the tutorial is a bit confusing for me.

**Comment by Taihenc** [comment]
OpenDrop is running on [OWL](https://github.com/seemoo-lab/owl), so make sure you have OWL running on your devices. To get OWL, you have either to clone the repo and compile it yourself or use a [compiled](https://github.com/bodaay/GoOpenDrop/tree/master/Compiled_OWL) one. After that, you install OpenDrop via pip.

In order to start OWL successfully, make sure your WIFI-card passes the [requirements](https://github.com/seemoo-lab/owl/blob/master/README.md#requirements) (and maybe turn off your WIFI-interface before running OWL).
